mpapws/src/Entity/BandeDessinee.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BandeDessineeRepository")
 */
class BandeDessinee
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Titre;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Auteur;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $Genre;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $SousGenre;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="saBandeDessinee", orphanRemoval=true)
     */
    private $sesCommentaires;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Notes", mappedBy="saBandeDessinee", orphanRemoval=true)
     */
    private $sesNotes;

    /**
     * @ORM\Column(type="datetime")
     */
    private $DateDeParution;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $NoteMoyenne;

    /**
     * @ORM\Column(type="integer")
     */
    private $estPopulaire;

    public function __construct()
    {
        $this->sesCommentaires = new ArrayCollection();
        $this->sesNotes = new ArrayCollection();
        $this->setNoteMoyenne();
        $this->verifieEstPopulaire();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->Titre;
    }

    public function setTitre(string $Titre): self
    {
        $this->Titre = $Titre;

        return $this;
    }

    public function getAuteur(): ?string
    {
        return $this->Auteur;
    }

    public function setAuteur(string $Auteur): self
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->Genre;
    }

    public function setGenre(string $Genre): self
    {
        $this->Genre = $Genre;

        return $this;
    }

    public function getSousGenre(): ?string
    {
        return $this->SousGenre;
    }

    public function setSousGenre(string $SousGenre): self
    {
        $this->SousGenre = $SousGenre;

        return $this;
    }

    /**
     * @return Collection|Commentaire[]
     */
    public function getSesCommentaires(): Collection
    {
        return $this->sesCommentaires;
    }

    public function addSesCommentaire(Commentaire $sesCommentaire): self
    {
        if (!$this->sesCommentaires->contains($sesCommentaire)) {
            $this->sesCommentaires[] = $sesCommentaire;
            $sesCommentaire->setSaBandeDessinee($this);
        }

        return $this;
    }

    public function removeSesCommentaire(Commentaire $sesCommentaire): self
    {
        if ($this->sesCommentaires->contains($sesCommentaire)) {
            $this->sesCommentaires->removeElement($sesCommentaire);
            // set the owning side to null (unless already changed)
            if ($sesCommentaire->getSaBandeDessinee() === $this) {
                $sesCommentaire->setSaBandeDessinee(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Notes[]
     */
    public function getSesNotes(): Collection
    {
        return $this->sesNotes;
    }

    public function addSesNote(Notes $sesNote): self
    {
        if (!$this->sesNotes->contains($sesNote)) {
            $this->sesNotes[] = $sesNote;
            $sesNote->setSaBandeDessinee($this);
        }

        $this->setNoteMoyenne();
        $this->verifieEstPopulaire();
        return $this;
    }

    public function removeSesNote(Notes $sesNote): self
    {
        if ($this->sesNotes->contains($sesNote)) {
            $this->sesNotes->removeElement($sesNote);
            // set the owning side to null (unless already changed)
            if ($sesNote->getSaBandeDessinee() === $this) {
                $sesNote->setSaBandeDessinee(null);
            }
        }

        $this->setNoteMoyenne();
        return $this;
    }

    public function getDateDeParution(): ?\DateTimeInterface
    {
        return $this->DateDeParution;
    }

    public function setDateDeParution(\DateTimeInterface $DateDeParution): self
    {
        $this->DateDeParution = $DateDeParution;

        return $this;
    }

    public function getLivrePDF(): ?string
    {
        return '/data/' . $this->getId() . '/livre.pdf';
    }

    public function getPlanche1(): ?string
    {
        return '/data/' . $this->getId() . '/p1.jpg';
    }

    public function getPlanche2(): ?string
    {
        return '/data/' . $this->getId() . '/p2.jpg';
    }

    public function getPlanche3(): ?string
    {
        return '/data/' . $this->getId() . '/p3.jpg';
    }

    public function getPlanche4(): ?string
    {
        return '/data/' . $this->getId() . '/p4.jpg';
    }

    public function getPlanche5(): ?string
    {
        return '/data/' . $this->getId() . '/p5.jpg';
    }

    public function getAffiche(): ?string
    {
        return '/data/' . $this->getId() . '/affiche.jpg';
    }

    public function getNbCommentaires(){

        /* Fonction qui récupère le nombre de commentaires pour une BD */

        $Commentaires = $this->getSesCommentaires();
        $nbCommentaires = 0;

        foreach($Commentaires as $Commentaire)
        {
            $nbCommentaires += 1;
        }

        return $nbCommentaires;
    }

    public function getNbNotes(){

        /* Fonction qui récupère le nombre de commentaires pour une BD */

        $Notes = $this->getSesNotes();
        $nbNotes = 0;

        foreach($Notes as $Note)
        {
            $nbNotes += 1;
        }

        return $nbNotes;
    }

    public function getNoteMoyenne(){

        /* Fonction qui récupère une note moyenne à partir d'une liste de notes */

        $Notes = $this->getSesNotes();
        $NoteMoyenne = 0;
        $i = 0;

        foreach($Notes as $Note)
        {
            $NoteMoyenne += $Note->getValeur();
            $i++;
        }
        if ($i != 0){
            $NoteMoyenne = $NoteMoyenne / $i;
            $NoteMoyenne = number_format($NoteMoyenne, 2, ',', ' ');
        }else $NoteMoyenne = null;



        $this->setNoteMoyenne();
        return $this->NoteMoyenne;
    }

    public function setNoteMoyenne(): self
    {
        /* Fonction qui set sa note moyenne */

        $Notes = $this->getSesNotes();
        $NoteMoyenne = 0;
        $i = 0;

        foreach($Notes as $Note)
        {
            $NoteMoyenne += $Note->getValeur();
            $i++;
        }
        if ($i != 0){
            $NoteMoyenne = $NoteMoyenne / $i;
            $NoteMoyenne = number_format($NoteMoyenne, 2, ',', ' ');
        }
        else $NoteMoyenne = -1;

        $this->NoteMoyenne = $NoteMoyenne;

        return $this;
    }

    public function getEstPopulaire(): ?int
    {
        return $this->estPopulaire;
    }

    public function setEstPopulaire(int $estPopulaire): self
    {
        $this->estPopulaire = $estPopulaire;

        return $this;
    }

    public function verifieEstPopulaire()
    {
        if($this->getNoteMoyenne() >= 4.00 && $this->getNbNotes() >= 10)
        {
            $this->setEstPopulaire(1);
        }
        else
        {
            $this->setEstPopulaire(0);
        }
    }

}

mpapws/src/Entity/Commentaire.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentaireRepository")
 */
class Commentaire
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $Auteur;

    /**
     * @ORM\Column(type="string", length=250)
     */
    private $Contenu;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\BandeDessinee", inversedBy="sesCommentaires")
     * @ORM\JoinColumn(nullable=false)
     */
    private $saBandeDessinee;

    /**
     * @ORM\Column(type="datetime")
     */
    private $Date;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuteur(): ?string
    {
        return $this->Auteur;
    }

    public function setAuteur(string $Auteur): self
    {
        $this->Auteur = $Auteur;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->Contenu;
    }

    public function setContenu(string $Contenu): self
    {
        $this->Contenu = $Contenu;

        return $this;
    }

    public function getSaBandeDessinee(): ?BandeDessinee
    {
        return $this->saBandeDessinee;
    }

    public function setSaBandeDessinee(?BandeDessinee $saBandeDessinee): self
    {
        $this->saBandeDessinee = $saBandeDessinee;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->Date;
    }

    public function setDate(\DateTimeInterface $Date): self
    {
        $this->Date = $Date;

        return $this;
    }
}

mpapws/templates/pages/BDDetaillee.html.twig
{%  extends 'base.html.twig' %}

{% block body  %}
    </br>
    <div class="row justify-content-between align-items-center">
        {# Zone de gauche #}
        <div class="column">
            <img src="{{ BandeDessinee.getAffiche() }}" style="width: 200px;">
            <p class="ml-2">
                {% if BandeDessinee.getSesNotes|length != 0%}
                Note :  {{ BandeDessinee.getNoteMoyenne() }} / 5 sur {{ BandeDessinee.getSesNotes()|length }} notes
                {% else %}
                    Aucune note
                {% endif %}
            </p>
            <p> Ajouter une note</p>
            {{ form_start(formNote) }}
            <div class="column text-center form-note">
                {{ form_row(formNote.Valeur) }}
                {{ form_row(formNote.save) }}
            </div>
            {{ form_end(formNote) }}

        </div>
        {# Zone de droite #}
        <div class="column mx-auto text-center">
            <p> AUTEUR {{ BandeDessinee.getAuteur() }} • PARUTION {{ BandeDessinee.getDateDeParution()|date("d/m/Y") }} • THEME {{ BandeDessinee.getGenre() }} {{ BandeDessinee.getSousGenre() }}</p>
            <h1 class="BD-title"> {{ BandeDessinee.getTitre() }} </h1>
            <p class="BD-Description"> {{ BandeDessinee.getDescription() }} </p>

        </div>

        <div class="column">
            <button type="button" class="btn button-download" onclick="window.open('{{ BandeDessinee.getLivrePDF() }}', '_blank')"> Ouvrir la BD</button>
        </div>

    </div>

    {# Zone des planches #}
    <div class="card mx-auto div-planche" style="margin-top: 20px;">
        <ul class="list-group list-group-horizontal-lg d-flex justify-content-around">
            {% for Planche in Planches %}
                <li class="list-group-item d-flex justify-content-between align-items-center " style="margin: 5px;">
                    <img src="{{ Planche }}" class="planche-img">   <!-- planches en fonction des id -->
                </li>
            {% endfor %}
        </ul>
    </div>


    {# Zone des Commentaires #}
    </br> </br>
    <div class="detailcomment-separator"> </div>
    </br>
    <p> {{ nbCommentaires }} Commentaires</p>
    </br>

    <section class="comments">
        <div class="form-comment">
            {{ form_start(formComment) }}
                {{ form_row(formComment.Auteur) }}
                <div class="form-comment2 row  align-items-center">
                    {{ form_row(formComment.Contenu) }}
                    {{ form_row(formComment.save) }}
                </div>
            {{ form_end(formComment) }}
        </div>

        </br>

        {% for Commentaire in Commentaires  %}
        <article class="comment">
            <div class="comment-body">
                <div class="text comment-border">
                    <p class="comment-content"> {{ Commentaire.getContenu() }} </p>
                </div>
                <p class="attribution">par {{ Commentaire.getAuteur() }} le {{ Commentaire.getDate() |date("d/m/Y")}} a {{ Commentaire.getDate() |date("H:i:s")}}</p>
            </div>
        </article>
        {% endfor %}
    </section>

{% endblock %}

mpapws/templates/pages/bd_detaillee.html.twig
{%  extends 'base.html.twig' %}

{% block body  %}
    </br>
    <div class="row justify-content-between align-items-center">
        {# Zone de gauche #}
        <div class="column">
            <img src="{{ BandeDessinee.getAffiche() }}" style="width: 200px;">
            <p class="ml-2">
                {% if BandeDessinee.getSesNotes|length != 0%}
                Note :  {{ BandeDessinee.getNoteMoyenne() }} / 5 sur {{ BandeDessinee.getSesNotes()|length }} notes
                {% else %}
                    Aucune note
                {% endif %}
            </p>
            <p> Ajouter une note</p>
            {{ form_start(formNote) }}
            <div class="column text-center form-note">
                {{ form_row(formNote.Valeur) }}
                {{ form_row(formNote.save) }}
            </div>
            {{ form_end(formNote) }}

        </div>
        {# Zone de droite #}
        <div class="column mx-auto text-center">
            <p> AUTEUR {{ BandeDessinee.getAuteur() }} • PARUTION {{ BandeDessinee.getDateDeParution()|date("d/m/Y") }} • THEME {{ BandeDessinee.getGenre() }} {{ BandeDessinee.getSousGenre() }}</p>
            <h1 class="BD-title"> {{ BandeDessinee.getTitre() }} </h1>
            <p class="BD-Description"> {{ BandeDessinee.getDescription() }} </p>

        </div>

        <div class="column">
            <button type="button" class="btn button-download" onclick="window.open('{{ BandeDessinee.getLivrePDF() }}', '_blank')"> Ouvrir la BD</button>
        </div>

    </div>

    {# Zone des planches #}
    <div class="card mx-auto div-planche" style="margin-top: 20px;">
        <ul class="list-group list-group-horizontal-lg d-flex justify-content-around">
            {% for Planche in Planches %}
                <li class="list-group-item d-flex justify-content-between align-items-center " style="margin: 5px;">
                    <img src="{{ Planche }}" class="planche-img">   <!-- planches en fonction des id -->
                </li>
            {% endfor %}
        </ul>
    </div>


    {# Zone des Commentaires #}
    </br> </br>
    <div class="detailcomment-separator"> </div>
    </br>
    <p> {{ nbCommentaires }} Commentaires</p>
    </br>

    <section class="comments">
        <div class="form-comment">
            {{ form_start(formComment) }}
                {{ form_row(formComment.Auteur) }}
                <div class="form-comment2 row  align-items-center">
                    {{ form_row(formComment.Contenu) }}
                    {{ form_row(formComment.save) }}
                </div>
            {{ form_end(formComment) }}
        </div>

        </br>

        {% for Commentaire in Commentaires  %}
        <article class="comment">
            <div class="comment-body">
                <div class="text comment-border">
                    <p class="comment-content"> {{ Commentaire.getContenu() }} </p>
                </div>
                <p class="attribution">par {{ Commentaire.getAuteur() }} le {{ Commentaire.getDate() |date("d/m/Y")}} a {{ Commentaire.getDate() |date("H:i:s")}}</p>
            </div>
        </article>
        {% endfor %}
    </section>

{% endblock %}

mpapws/templates/pages/formulaire.html.twig
{%  extends 'base.html.twig' %}

{% block body  %}
        <h1 style="text-align: center; margin-top: 1em; color : #1089FF; font-size: 38pt">Mettre en ligne une BD</h1>
        <h2 style="margin-top: 3em; font-size: 18pt">Veuillez compléter le formulaire et cliquer sur "Valider"</h2>
        <hr>
        <div style="margin-bottom: 1em" class="row">
                <div class="form-gauche col-sm-6">
                        {{ form_start(form) }}
                        {{ form_row(form.titre) }}
                        <br>
                        {{ form_row(form.auteur) }}
                        <br>
                        <div class="description-UploadFichier" style=".custom-file::after{content: 'blabla';}">
                                {{ form_row(form.description) }}
                        </div>
                </div>
                <div class="form-droite col-sm-6">
                        {{ form_row(form.genre) }}
                        <br>
                        {{ form_row(form.sousGenre) }}
                        <br>
                        {{ form_row(form.LivrePDF) }}
                </div>
        </div>
        <hr>
        <div class="row">
                <div style="margin: auto">
                        {{ form_row(form.save) }}
                        {{ form_end(form) }}
                </div>
        </div>


{% endblock %}

mpapws/templates/pages/home.html.twig
{%  extends 'base.html.twig' %}

{% block body  %}



        <h2 class="home-title"> Tendances</h2>

    {# Zone des BD Tendances #}
        <div class="tendance-zone">
            {% for  BDTendance in BDTendances%}
                <div class="la-BD-tendance">
                    <a href="{{ path('listeBDSousGenre', {'genre' : BDTendance.getGenre(), 'sousGenre' : BDTendance.getSousGenre(),'page' : 1}) }}"> <p class="sous-genre"> {{ BDTendance.getSousGenre() }}</p> </a>
                     <a href="{{ path('BDDetaillee', {'id' : BDTendance.getId(), 'genre' : BDTendance.getGenre() }) }}"> <img src="{{ BDTendance.getAffiche() }}" class="mr-3 bdtendance-affiche" alt="affiche_test.jpg"> </a>
                    <a href="{{ path('BDDetaillee', {'id' : BDTendance.getId(), 'genre' : BDTendance.getGenre() }) }}" class="bdtendance-title-link"> <p class="bdtendance-title"> {{ BDTendance.getTitre() }}</p> </a>
                     <p class="bdtendance-author"> par {{ BDTendance.getAuteur() }}</p>
                </div>
            {% endfor %}

            {% if BDTendances|length > 4 %}
            <button type="button" onclick="window.location.href='{{ path('listeBDGenre', {'genre' : 'BD', 'page' : 1}) }}'" class="bdtendance-voirplus">Voir plus</button>
            {% endif %}
        </div>

    {# Zone des Mangas Tendances #}
    <div class="tendance-zone">
        {% for  MangaTendance in MangasTendances%}
            <div class="la-BD-tendance">
                <a href="{{ path('listeBDSousGenre', {'genre' : MangaTendance.getGenre(), 'sousGenre' : MangaTendance.getSousGenre(),'page' : 1}) }}"> <p class="sous-genre"> {{ MangaTendance.getSousGenre() }}</p> </a>
                <a href="{{ path('BDDetaillee', {'id' : MangaTendance.getId(), 'genre' : MangaTendance.getGenre() }) }}" style="display: inline;"> <img src="{{ MangaTendance.getAffiche() }}" class="mr-3 bdtendance-affiche" alt="affiche_test.jpg"> </a>
                <a href="{{ path('BDDetaillee', {'id' : MangaTendance.getId(), 'genre' : MangaTendance.getGenre() }) }}" class="bdtendance-title-link"> <p class="bdtendance-title"> {{ MangaTendance.getTitre() }}</p> </a>
                <p class="bdtendance-author"> par {{ MangaTendance.getAuteur() }}</p>
            </div>
        {% endfor %}

        {% if MangasTendances|length > 4 %}
         <button type="button" onclick="window.location.href='{{ path('listeBDGenre', {'genre' : 'Mangas', 'page' : 1}) }}'" class="bdtendance-voirplus">Voir plus</button>
        {% endif %}
    </div>

    {# Zone des Comics Tendances #}
    <div class="tendance-zone">
        {% for  ComicTendance in ComicsTendances%}
            <div class="la-BD-tendance">
                <a href="{{ path('listeBDSousGenre', {'genre' : ComicTendance.getGenre(), 'sousGenre' : ComicTendance.getSousGenre(),'page' : 1}) }}"> <p class="sous-genre"> {{ ComicTendance.getSousGenre() }} </p> </a>
                <a href="/{{ ComicTendance.getGenre() }}/{{ ComicTendance.getId() }}"> <img src="{{ ComicTendance.getAffiche() }}" class="mr-3 bdtendance-affiche"  alt="affiche_test.jpg"> </a>
                <a href="/{{ ComicTendance.getGenre() }}/{{ ComicTendance.getId() }}" class="bdtendance-title-link">  <p class="bdtendance-title"> {{ ComicTendance.getTitre() }} </p> </a>
                <p class="bdtendance-author"> par {{ ComicTendance.getAuteur() }}</p>
            </div>
        {% endfor %}

        {% if ComicsTendances|length > 4 %}
         <button type="button" onclick="window.location.href='{{ path('listeBDGenre', {'genre' : 'Comics', 'page' : 1}) }}'" class="bdtendance-voirplus">Voir plus</button>
        {% endif %}
    </div>



{% endblock %}

mpapws/templates/pages/listeBD.html.twig
{%  extends 'base.html.twig' %}


{% block body  %}

    {% if BandeDessinees is not empty %}
        <br/>
        <h2 class="text-center liste-title"> Vous consultez la liste des {{ GenreToString }}</h2>
        <br/>
    {% endif %}

    <ul class="list-unstyled">
        {% set i = 0 %}
        {% for BandeDessinee in BandeDessinees  %}

            <li class="media my-4">
                <a href="/BD/{{ BandeDessinee.getId() }}"> <img src="{{ BandeDessinee.getAffiche() }}" class="mr-3" style="height: 200px" alt="affiche_test.jpg"> </a>
                <div class="media-body">
                    <a href="/BD/{{ BandeDessinee.getId() }}" class="BDlist-link"><h5 class="mt-0 mb-1">{{ BandeDessinee.getTitre() }}</h5></a>
                    <p class="font-weight-bold">{{ BandeDessinee.getDateDeParution()|date("d/m/Y") }} •

                        {% if BandeDessinee.getSesNotes()|length != 0 %}
                            {{ BandeDessinee.getNoteMoyenne() }} / 5</p>
                        {% else  %}
                            Aucune note</p>
                        {% endif %}

                    <p>{{ BandeDessinee.getDescription() }}</p>
                </div>
            </li>

        {% endfor %}
    </ul>


    {# Si jamais il n'y a pas de BD dans la liste #}
    {% if BandeDessinees is empty %}
            <div class="row justify-content-between align-items-center" style="width: 600px;">
                <img src="/img/noresult.png" style="width: 200px;">
                <div class=column">
                    <h1 class="noresult-title"> OOPS ! </h1>
                    <h3> Aucun résultat trouvé</h3>
                </div>
            </div>
            <br/>
            <button type="button" class="btn button-download" onclick="window.location.href='http://mpapws.loc:9999/'"> Retour à la page d'accueil</button>
        {% endif %}


{% endblock %}

mpapws/templates/pages/liste_bd.html.twig
{%  extends 'base.html.twig' %}


{% block body  %}

    {% if BandeDessinees is not empty %}
        <br/>
        <h2 class="text-center liste-title"> Vous consultez la liste des {{ GenreToString }}</h2>
        <br/>
    {% endif %}

    <ul class="list-unstyled">
        {% set i = 0 %}
        {% for BandeDessinee in BandeDessinees  %}

            <li class="media my-4">
                <a href="{{ path('BDDetaillee', {'id' : BandeDessinee.getId(), 'genre' : BandeDessinee.getGenre() }) }}"> <img src="{{ BandeDessinee.getAffiche() }}" class="mr-3" style="height: 200px" alt="affiche_test.jpg"> </a>
                <div class="media-body">
                    <a href="{{ path('BDDetaillee', {'id' : BandeDessinee.getId(), 'genre' : BandeDessinee.getGenre() }) }}" class="BDlist-link"><h5 class="mt-0 mb-1">{{ BandeDessinee.getTitre() }}</h5></a>
                    <p class="font-weight-bold">{{ BandeDessinee.getDateDeParution()|date("d/m/Y") }} •

                        {% if BandeDessinee.getSesNotes()|length != 0 %}
                            {{ BandeDessinee.getNoteMoyenne() }} / 5</p>
                        {% else  %}
                            Aucune note</p>
                        {% endif %}

                    <p>{{ BandeDessinee.getDescription() }}</p>
                </div>
            </li>

        {% endfor %}
    </ul>




{% endblock %}

mpapws/templates/pages/no_result.html.twig
{%  extends 'base.html.twig' %}

{% block body  %}

    <div class="row justify-content-between align-items-center" style="width: 600px;">
        <img src="/img/noresult.png" style="width: 200px;">
            <div class=column">
                <h1 class="noresult-title"> OOPS ! </h1>
                <h3> Aucun résultat trouvé</h3>
            </div>
    </div>
    <br/>
    <button type="button" class="btn button-download" onclick="window.location.href='http://mpapws.loc:9999/'"> Retour à la page d'accueil</button>


{% endblock %}

mpapws/templates/pages/task_success.html.twig
{%  extends 'base.html.twig' %}

{% block body  %}

    <div class="row justify-content-between align-items-center" style="width: 600px;">
        <img src="/img/success.png" style="width: 200px;">
        <div class=column">
            <h1 class="noresult-title"> MERCI ! </h1>
            <h3> Votre BD a bien été enregistrée !</h3>
        </div>
    </div>
    <br/>
    <button type="button" class="btn button-download" onclick="window.location.href='http://mpapws.loc:9999/'"> Retour à la page d'accueil</button>
    <button type="button" class="btn button-download" onclick="window.location.href='{{ path('BDDetaillee', {'id' : BandeDessinee.getId(), 'genre' : BandeDessinee.getGenre() }) }}'"> Visionnez votre BD</button>

{% endblock %}